YSYX_HOME=/home/chang/programs/ysyx-workbench
NAME?= default
PROJECT_DIR= $(YSYX_HOME)/projects/$(NAME)


default: 
	@echo "Please execute 'make run'"

build_project:
	$(shell mkdir $(PROJECT_DIR))
	$(shell cp -r ./template/* $(PROJECT_DIR))