YSYX_HOME=/home/chang/programs/ysyx-workbench



all:
	@echo "Making the project..."

build:
	$(shell mkdir $(PROJECT) \
			$(PROJECT)/csrc \
			$(PROJECT)/vsrc	\
			$(PROJECT)/constr\
			$(PROJECT)/constr\
			)

clean:
	rm -rf $(PROJECT)

include $(YSYX_HOME)/Makefile  $(NVBOARD_HOME)/scripts/nvboard.mk




